blank_issues_enabled: false
contact_links:
    - name: ðŸ—£ Ask a Question, Discuss
      url: https://github.com/eslint/js/discussions
      about: Get help using ESLint
    - name: Discord Server
      url: https://eslint.org/chat
      about: Talk with the team
